"""create new planet and read all planets endpoint with Planet Model

Revision ID: 656f92f287d9
Revises: 
Create Date: 2025-04-24 12:01:43.809719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656f92f287d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('moon_count', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planet')
    # ### end Alembic commands ###
