"""added moon

Revision ID: bd797b1e53d5
Revises: 656f92f287d9
Create Date: 2025-05-13 16:13:10.304001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd797b1e53d5'
down_revision = '656f92f287d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('orbital_period', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moon_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'moon', ['moon_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('moon_id')

    op.drop_table('moon')
    # ### end Alembic commands ###
